server:
  port: ${services.front50.port:8080}
  address: 0.0.0.0

aws:
  simpleDBEnabled: ${providers.aws.simpleDBEnabled:false}
  defaultSimpleDBDomain: ${providers.aws.defaultSimpleDBDomain}

cassandra:
  enabled: false

spinnaker:
  cassandra:
    enabled: ${services.front50.cassandra.enabled}
  redis:
    enabled: ${services.front50.redis.enabled}
    host: ${services.redis.host}
    port: ${services.redis.port}
  gcs:
    enabled: ${services.front50.gcs.enabled}
    project: ${services.front50.gcs.project}
    jsonPath: /root/.kube/account.json # Don't change this
    rootFolder: ${services.front50.bucket_root}
    bucket: ${services.front50.storage_bucket}
  s3:
    enabled: ${services.front50.s3.enabled}
    rootFolder: ${services.front50.bucket_root}
    bucket: ${services.front50.storage_bucket}
